"use client"
import { UserDataContextProvider } from '@/store/movie.context'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { DataContextProvider } from '@/store/filter.context'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserDataContextProvider>
          <DataContextProvider>
            {children}
          </DataContextProvider>
        </UserDataContextProvider>
      </body>
    </html>
  )
}
